language: php

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

.Test: &test
  script:
    - export MAKE_PSALM_OPTIONS="--shepherd"
    - export MAKE_PHPUNIT_OPTIONS="--coverage-clover=coverage.xml"
    - if [ -z "$dependencies" ]; then composer update --prefer-dist --no-progress; fi;
    - if [ "$dependencies" = "lowest" ]; then composer update --prefer-dist --no-progress --prefer-lowest -n; fi;
    - make test
    - bash <(curl -s https://codecov.io/bash)

.Lint Editorconfig: &editor_config
  install:
    - npm install -g editorconfig-checker@^2.0
  script:
    - editorconfig-checker

jobs:
  include:
    - <<: *editor_config
      name: Lint Editorconfig
      php: 7.4
    - <<: *test
      name: Unit Tests (PHP 7.4, highest)
      php: 7.4
    - <<: *test
      name: Unit Tests (PHP 7.3, highest)
      php: 7.3
    - <<: *test
      name: Unit Tests (PHP 7.4, lowest)
      php: 7.4
      env: dependencies=lowest
    - <<: *test
      name: Unit Tests (PHP 7.3, lowest)
      php: 7.3
      env: dependencies=lowest
